name: "Check-PR-For-2-Accessibility-Images"
description: "Checks that a PR has two accessibility images"
author: "Mike DelGaudio"
branding:
  icon: "git-pull-request"
  color: "gray-dark"
inputs:
  GITHUB_TOKEN:
    description: "REQUIRED GitHub Token"
  checkForImages:
    description: "Boolean value 'true' or 'false' to check PR for image"
  checkPrTitle:
    description: "Boolean value 'true' or 'false' to check if PR title starts with HRO-<JIRA#> or HROIMP-<JIRA#>"
  ignoreDependabot:
    description: "Boolean value 'true' or 'false' to ignore PRs authored by Dependabot"

runs:
  using: "node16"
  main: "dist/index.js"
