name: "Check-PR-For-Image"
description: "Checks that a PR has an attached image"
author: "Mike DelGaudio"
branding:
  icon: "git-pull-request"
  color: "gray-dark"
inputs:
  github-token:
    description: "REQUIRED GitHub Token"
  checkForImage:
    description: "Boolean value 'true' or 'false' to check PR for image"

runs:
  using: "node16"
  main: "dist/index.js"
